//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthHere
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_sctructure = new HashSet<order_sctructure>();
        }
    
        public int order_id { get; set; }
        public int user_id { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> finall_price { get; set; }
        public Nullable<int> pharmacy_id { get; set; }
    
        public virtual pharmacy pharmacy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_sctructure> order_sctructure { get; set; }
        public virtual user user { get; set; }
    }
}
